// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hwecosystemAPI.Models;

namespace hwecosystemAPI.Migrations
{
    [DbContext(typeof(hwecosystemDbContext))]
    [Migration("20200904234409_mig4")]
    partial class mig4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hwecosystemAPI.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompanyShare")
                        .HasColumnType("float");

                    b.Property<double>("Contibution")
                        .HasColumnType("float");

                    b.Property<Guid>("Contributor_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsComfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<double>("LogisticsShare")
                        .HasColumnType("float");

                    b.Property<double>("RegistrationFee")
                        .HasColumnType("float");

                    b.Property<double>("SoftDevTechShare")
                        .HasColumnType("float");

                    b.Property<string>("TypeOfStream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UpLinersShare")
                        .HasColumnType("float");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transactions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trxref")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.Contributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BirthDay")
                        .HasColumnType("int");

                    b.Property<int>("BirthMonth")
                        .HasColumnType("int");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genotype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<string>("LGAOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOKAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOKNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOKPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOKRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nChildren")
                        .HasColumnType("int");

                    b.Property<int>("nDescendants")
                        .HasColumnType("int");

                    b.Property<int>("nGrandChildren")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Contributor_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<string>("CycleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cycle_Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThreshHoldReached")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.IdentityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityModels");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desendants_Ids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<string>("LevelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level_Index")
                        .HasColumnType("int");

                    b.Property<double>("PaymentReceived")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.Pishon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualPishonIndex")
                        .HasColumnType("int");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<Guid>("contributorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("contributorIndex")
                        .HasColumnType("int");

                    b.Property<bool>("isLevelFiveComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelFiveEntitlementPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelFourComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelFourEntitlementPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelOneComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelOneEntitlementPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelSevenComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelSevenEntitlementPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelSixComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelSixEntitlementPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelThreeComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelThreeEntitlementPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelTwoComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("isLevelTwoEntitlementPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Pishons");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.PishonRefugeeCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<Guid>("contributorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("contributorIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PishonRefugeeCenters");
                });

            modelBuilder.Entity("hwecosystemAPI.Models.RefugeCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedDay")
                        .HasColumnType("int");

                    b.Property<int>("CreatedMonth")
                        .HasColumnType("int");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsPhotographUploaded")
                        .HasColumnType("bit");

                    b.Property<Guid>("contributorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("contributorIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefugeCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
